#demonstrate how to use inline json 6902 patches. But there seems to be a flux bug or missing feature
#because flux errors out and complains unexpected 'patch'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../flux-system-base
patchesJSON6902:
  - target:
      kind: GitRepository
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/url
        value: ssh://git@github.com/geoffhendrey/fleet-infra
  - target:
      kind: Kustomization
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/path
        value: ./clusters/mycluster
